// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/account.dart';
import 'model/movement.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 7125413560799074345),
      name: 'Account',
      lastPropertyId: const IdUid(5, 7160523221725817897),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8235784791530254553),
            name: 'balance',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(2, 7330821940429415724),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 5497726718756106915),
            name: 'planned',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 5277647252981104953),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(5, 7160523221725817897),
            name: 'typeId',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(1, 8444388186473723729),
            name: 'movements',
            targetId: const IdUid(2, 4795105174811773723))
      ],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 4795105174811773723),
      name: 'Movement',
      lastPropertyId: const IdUid(7, 7826717817108584712),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6715634523243968162),
            name: 'total',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(2, 6466815438212888281),
            name: 'description',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 88133066248017546),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(4, 7153867726491825934),
            name: 'toAccountId',
            type: 11,
            flags: 520,
            indexId: const IdUid(1, 3125017304694943687),
            relationTarget: 'Account'),
        ModelProperty(
            id: const IdUid(6, 5038166749616400197),
            name: 'date',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 7826717817108584712),
            name: 'fromAccountId',
            type: 11,
            flags: 520,
            indexId: const IdUid(3, 2507110557791474098),
            relationTarget: 'Account')
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 4795105174811773723),
      lastIndexId: const IdUid(3, 2507110557791474098),
      lastRelationId: const IdUid(1, 8444388186473723729),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [2227327365898950886],
      retiredPropertyUids: const [8346561184496968783],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Account: EntityDefinition<Account>(
        model: _entities[0],
        toOneRelations: (Account object) => [],
        toManyRelations: (Account object) =>
            {RelInfo<Account>.toMany(1, object.id): object.movements},
        getId: (Account object) => object.id,
        setId: (Account object, int id) {
          object.id = id;
        },
        objectToFB: (Account object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(6);
          fbb.addFloat64(0, object.balance);
          fbb.addOffset(1, nameOffset);
          fbb.addFloat64(2, object.planned);
          fbb.addInt64(3, object.id);
          fbb.addInt64(4, object.typeId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Account(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
              balance:
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 4, 0),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              planned:
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0),
              typeId:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0));
          InternalToManyAccess.setRelInfo(object.movements, store,
              RelInfo<Account>.toMany(1, object.id), store.box<Account>());
          return object;
        }),
    Movement: EntityDefinition<Movement>(
        model: _entities[1],
        toOneRelations: (Movement object) =>
            [object.toAccount, object.fromAccount],
        toManyRelations: (Movement object) => {},
        getId: (Movement object) => object.id,
        setId: (Movement object, int id) {
          object.id = id;
        },
        objectToFB: (Movement object, fb.Builder fbb) {
          final descriptionOffset = fbb.writeString(object.description);
          fbb.startTable(8);
          fbb.addFloat64(0, object.total);
          fbb.addOffset(1, descriptionOffset);
          fbb.addInt64(2, object.id);
          fbb.addInt64(3, object.toAccount.targetId);
          fbb.addInt64(5, object.date.millisecondsSinceEpoch);
          fbb.addInt64(6, object.fromAccount.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Movement(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
              date: DateTime.fromMillisecondsSinceEpoch(
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0)))
            ..total =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..description = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '');
          object.toAccount.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          object.toAccount.attach(store);
          object.fromAccount.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.fromAccount.attach(store);
          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Account] entity fields to define ObjectBox queries.
class Account_ {
  /// see [Account.balance]
  static final balance =
      QueryDoubleProperty<Account>(_entities[0].properties[0]);

  /// see [Account.name]
  static final name = QueryStringProperty<Account>(_entities[0].properties[1]);

  /// see [Account.planned]
  static final planned =
      QueryDoubleProperty<Account>(_entities[0].properties[2]);

  /// see [Account.id]
  static final id = QueryIntegerProperty<Account>(_entities[0].properties[3]);

  /// see [Account.typeId]
  static final typeId =
      QueryIntegerProperty<Account>(_entities[0].properties[4]);

  /// see [Account.movements]
  static final movements =
      QueryRelationToMany<Account, Movement>(_entities[0].relations[0]);
}

/// [Movement] entity fields to define ObjectBox queries.
class Movement_ {
  /// see [Movement.total]
  static final total =
      QueryDoubleProperty<Movement>(_entities[1].properties[0]);

  /// see [Movement.description]
  static final description =
      QueryStringProperty<Movement>(_entities[1].properties[1]);

  /// see [Movement.id]
  static final id = QueryIntegerProperty<Movement>(_entities[1].properties[2]);

  /// see [Movement.toAccount]
  static final toAccount =
      QueryRelationToOne<Movement, Account>(_entities[1].properties[3]);

  /// see [Movement.date]
  static final date =
      QueryIntegerProperty<Movement>(_entities[1].properties[4]);

  /// see [Movement.fromAccount]
  static final fromAccount =
      QueryRelationToOne<Movement, Account>(_entities[1].properties[5]);
}
